---
# handlers file for haproxy
- name: reload rsyslog
  service: name=rsyslog state=restarted
  tags: rsyslog

- name: reload haproxy
  service: name=haproxy state=restarted enabled=yes
  tags: haproxy
